package com.wodlog.app.data.entity

import java.time.Instant
import java.time.LocalDate
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Test

class WodEntityTest {
    @Test
    fun wodEntity_usesAutoGenerateDefaultIdAndRequiredFields() {
        val now = Instant.ofEpochMilli(1_777_777_777_000)
        val entity = WodEntity(
            date = LocalDate.of(2026, 5, 3),
            title = "Fran",
            type = WodType.FOR_TIME,
            createdAt = now,
            updatedAt = now
        )

        assertEquals(0L, entity.id)
        assertEquals(LocalDate.of(2026, 5, 3), entity.date)
        assertEquals("Fran", entity.title)
        assertEquals(WodType.FOR_TIME, entity.type)
        assertNull(entity.rawText)
        assertNull(entity.notes)
    }

    @Test
    fun movementEntity_allowsUnknownOptionalMetrics() {
        val entity = MovementEntity(
            wodId = 10L,
            movementName = "Pull-up",
            orderIndex = 0
        )

        assertEquals(0L, entity.id)
        assertEquals(10L, entity.wodId)
        assertEquals("Pull-up", entity.movementName)
        assertNull(entity.sectionId)
        assertNull(entity.weightKg)
        assertNull(entity.reps)
    }

    @Test
    fun wodResultEntity_defaultsRxStatusToUnknown() {
        val now = Instant.ofEpochMilli(1_777_777_777_000)
        val entity = WodResultEntity(
            wodId = 1L,
            scoreType = ScoreType.TIME,
            timeSeconds = 420,
            createdAt = now,
            updatedAt = now
        )

        assertEquals(1L, entity.wodId)
        assertEquals(ScoreType.TIME, entity.scoreType)
        assertEquals(420, entity.timeSeconds)
        assertEquals(RxStatus.UNKNOWN, entity.rxStatus)
    }
}
